### ISSUE TITLE
b站视频爬取进度条不显示，爬取分p太多的视频访问会被拒

### ISSUE THREAD

**Issue by shrikedehyperion** [wkunzhi/Python3-Spider#12]
我是在pycharm里面运行的，无论是下载单个视频还是分p很多的视频，下载进度条都不显示，把stdout换成print函数好像也没用，还有一个问题就是挂了代理也会被限制访问，我是用的自己的代理，被限了一次之后再换还是被限制。。。

**Comment by wkunzhi** [comment]
问题收到，后面抽空更新
