### ISSUE TITLE
make a suggestion

### ISSUE THREAD

**Issue by Foxgeek36** [wkunzhi/Python3-Spider#7]
dianping-font.py-parse_ttf函数中的name_list最好直接从函数install_ttf直接传值，以免在解析的时候出现NoneType错误

**Comment by wkunzhi** [comment]
那个地方我测试的时候写死了 忘了改回来， 谢谢提醒，已经修复

**Comment by wkunzhi** [comment]
另外现在字体通常页面有多套字库，调用的时候需要自行拓展一下要匹配对应字库获取文字。

**Comment by SnallQiu** [comment]
老哥美团酒店的X-FOR-WITH加密参数能搞不，js调试了一下午没找到生成的地方，网上说是内存里dump出来的，但是一直没搜到相关资料，期待回复谢谢。

**Comment by wkunzhi** [comment]
美团酒店不需要解这个参数

**Comment by Foxgeek36** [comment]
> 另外现在字体通常页面有多套字库，调用的时候需要自行拓展一下要匹配对应字库获取文字。

大佬的意思是在解析css链接之前，需根据所爬取的html页面提取出对应的css链接？ 也对，我发现有些页面中woff文件的数量和种类都是不一样的，即时提取即时解析

**Comment by wkunzhi** [comment]
含有字体的css链接只有一个，我写的代码会自动捕获页面的所有字体，你们只需要在调用的时候判断一下取哪个库的字体就行了

**Comment by Foxgeek36** [comment]
> 含有字体的css链接只有一个，我写的代码会自动捕获页面的所有字体，你们只需要在调用的时候判断一下取哪个库的字体就行了

soga，ok，我先做尝试，thank you my master ...

**Comment by kingking888** [comment]
可不可以把调用字体库变成通用接口------------------ 原始邮件 ------------------
发件人: "Foxgeek"<notifications@github.com>
发送时间: 2019年8月1日(星期四) 中午11:45
收件人: "wkunzhi/SpiderCrackDemo"<SpiderCrackDemo@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [wkunzhi/SpiderCrackDemo] make a suggestion (#7)


 
含有字体的css链接只有一个，我写的代码会自动捕获页面的所有字体，你们只需要在调用的时候判断一下取哪个库的字体就行了
  
soga，ok，我先做尝试，thank you my master ...
 
&mdash;

**Comment by Foxgeek36** [comment]
> 含有字体的css链接只有一个，我写的代码会自动捕获页面的所有字体，你们只需要在调用的时候判断一下取哪个库的字体就行了

大佬，我刚刚在测试的时候发现html中的css是变化的，频率是1次/天，所以还是得在每次下载字体文件之前匹配获取新的css链接；另外，我想请教个问题->file/font.py->FONT_LIST中的文本字体如何获得？1.使用OCR技术做图像识别的话准确率有高有低且要不断地训练模型，费力不讨好，因为我觉得匹配页面中的文字内容必须是100%正确率；2.手动获取有限的几百个汉字，但是不够自动化；Can you tell me the appropriate method, thank you!

**Comment by wkunzhi** [comment]
链接变化是正常的，所以你需要在页面中定位到哪个css链接放到，我demo中对象实例化那里，就会自动解析了。
`pf = ParseFontClass(你获取到的css链接)`

`pf .parse_ttf(神秘代码)`  就会return 中文给你了
